### ISSUE TITLE
After app update, the application says it needs an update

### ISSUE THREAD

**Issue by Mbenedic** [lurume84/bling-desktop#42]
Hello!  I love your app, however, I updated to 0.1.23 and every time I try to live view any of my cameras, it says "! An app update is required".  I have removed the old version 0.1.21 and reinstalled 0.1.23 and it still says the same thing.  Can you help?  Thank you!
![AppUpdateRequired](https://user-images.githubusercontent.com/69012293/88960658-d7177e80-d271-11ea-9c13-6bc9ab21a6e9.jpg)

**Comment by lurume84** [comment]
This message actually comes from Blink servers. It seems they have deprecated (again!) some endpoints. I will take a look today and let's hope we can recover this funcionality.

**Comment by lurume84** [comment]
I have released a new version that solves the problem, you should receive an automatic update to viewer0.1.21. Basically some endpoints are being deprecated because they do not identify the account, just network and camera. This may be a cybersecurity improvement or just because network and camera ids no longer identify a single user. By the way nice yard!

**Comment by Mbenedic** [comment]
Hi Luis!

Thank you for the update and thanks for the compliment on my yard!  That's
last year's picture, I should update that, looks much better this year! :)

As for the update, I still see 0.1.23 on the site and it was last updated
10 days ago.  They stopped the auto updates in this version.  :(  Is the
version you just updated on the site?

Thank you!
Marge

**Comment by Mbenedic** [comment]
Hi Luis!

I take that back!!  It just updated and live view is back!  Thank you!!!!

Marge

**Comment by Mbenedic** [comment]
Nice job!  Thanks again!
